#site_url: https://docs.3dbag.nl
site_name: 3D BAG
site_author: 3D geoinformation group
site_description: 3D BAG documentation
docs_dir: docs
site_dir: site
dev_addr: '127.0.0.1:8000'
nav:
  - Home: index.md
  - About:
    - about.md
    - 'Terms of Use': 'terms.md'
    - 'Changelog': 'changelog.md'
  - Attributes: attributes.md
  - "Viewer ": 'https://3dbag.nl'
theme:
  name: material
  favicon: img/3d-geoinfo-logo.svg
  logo: img/3d-geoinfo-logo.svg
  palette:
    primary: white
    accent: light-blue
  features:
    - navigation.tabs
    - navigation.instant
repo_url: https://github.com/tudelft3d/3dbag-docs
copyright: Copyright &copy; 2021 3D geoinformation group

extra:
  alternate:

    # Switch to English
    - name: English
      link: ./
      lang: en

    # Switch to Dutch
    - name: Nederlands
      link: /nl
      lang: nl

plugins:
  - search:
      lang:
        - en
        - du

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
