site_url: 'http://127.0.0.1:8000/nl'
site_name: '3D BAG'
site_author: '3D geoinformation research group'
site_description: '3D BAG productbeschrijving'
docs_dir: '../../docs/nl'
site_dir: '../../generated/nl'
#repo_url: https://github.com/tudelft3d/3dbag-docs
copyright: Copyright &copy; 2021 3D geoinformation research group, TU Delft
extra_css:
  - stylesheets/extra.css

theme:
  language: nl
  custom_dir: '../../overrides/'
  name: material
  favicon: assets/images/logo.svg
  logo: assets/images/logo.svg
  font:
    text: Inter
    code: Roboto Mono
  palette:
    primary: white
    accent: light-blue
  features:
    - navigation.tabs
    - navigation.instant

extra:
  alternate:

    - name: English
      link: /en/
      lang: en

    - name: Nederlands
      link: /nl/
      lang: nl

plugins:
  - search:
      lang: nl

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.snippets:
      check_paths: true
      base_path: "."

nav:
  - Overzicht:
    - 'Algemeen': index.md
    - 'Databronnen': overview/sources.md
    - 'Over ons': 'overview/group.md'
    - 'Release-opmerkingen': 'overview/release_notes.md'
  - Schema:
    - 'Algemene concepten': 'schema/concepts.md'
    - 'Datalagen': 'schema/layers.md'
    - 'Data-attributen': 'schema/attributes.md'
  - 'Dataformaten':
      - 'Webservices': 'delivery/webservices.md'
      - 'GeoPackage': 'delivery/gpkg.md'
      - 'CityJSON': 'delivery/cityjson.md'
      - 'PostgreSQL': 'delivery/postgresql.md'
      - 'Wavefront OBJ': 'delivery/obj.md'
  - 'Gebruiksvoorwaarden': 'copyright.md'
  - Contact: contact.md
  - 'Viewer': 'https://3dbag.nl'
