site_url: 'http://127.0.0.1:8000/nl'
site_name: '3D BAG'
site_author: '3D geoinformation research group'
site_description: '3D BAG productbeschrijving'
docs_dir: '../../docs/nl'
site_dir: '../../generated/nl'
#repo_url: https://github.com/tudelft3d/3dbag-docs
copyright: '<p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://3dbag.nl">Copyright &copy; 2021 - 3D BAG</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://3d.bk.tudelft.nl/">3D geoinformation research group</a> is licensed under <a href="http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"></a></p>'
extra_css:
  - stylesheets/extra.css

theme:
  language: nl
  custom_dir: '../../overrides/'
  name: material
  favicon: assets/images/logo.svg
  logo: assets/images/logo.svg
  font:
    text: Inter
    code: Roboto Mono
  palette:
    primary: white
    accent: light-blue
  features:
    - navigation.tabs
    - navigation.instant

extra:
  alternate:

    - name: English
      link: /en/
      lang: en

    - name: Nederlands
      link: /nl/
      lang: nl
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tudelft3d
    - icon: fontawesome/brands/github
      link: https://github.com/tudelft3d

plugins:
  - search:
      lang: nl

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.snippets:
      check_paths: true
      base_path: "."

nav:
  - Overzicht:
    - 'Algemeen': index.md
    - 'Databronnen': overview/sources.md
    - 'Over ons': 'overview/group.md'
    - 'Release-opmerkingen': 'overview/release_notes.md'
  - Schema:
    - 'Algemene concepten': 'schema/concepts.md'
    - 'Datalagen': 'schema/layers.md'
    - 'Data-attributen': 'schema/attributes.md'
  - 'Dataformaten':
      - 'Webservices': 'delivery/webservices.md'
      - 'GeoPackage': 'delivery/gpkg.md'
      - 'CityJSON': 'delivery/cityjson.md'
      - 'PostgreSQL': 'delivery/postgresql.md'
      - 'Wavefront OBJ': 'delivery/obj.md'
  - 'Gebruiksvoorwaarden': 'copyright.md'
  - Contact: contact.md
  - 'Viewer': 'https://3dbag.nl'
