site_name: '3D BAG'
site_author: '3D geoinformation group'
site_description: '3D BAG productbeschrijving'
docs_dir: '../../docs/nl'
site_dir: '../../generated/nl'
repo_url: https://github.com/tudelft3d/3dbag-docs
copyright: Copyright &copy; 2021 3D geoinformation group


theme:
  language: nl
  custom_dir: '../../overrides/'
  name: material
  favicon: assets/images/logo.svg
  logo: assets/images/logo.svg
  font:
    text: Inter
    code: Roboto Mono
  palette:
    primary: white
    accent: light-blue
  features:
    - navigation.tabs
    - navigation.instant

extra:
  alternate:

    - name: English
      link: /en/
      lang: en

    - name: Nederlands
      link: /nl/
      lang: nl

plugins:
  - search:
      lang: nl

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list

nav:
  - Overzicht: index.md
