site_name: '3D BAG'
site_author: '3D geoinformation research group'
site_description: '3D BAG documentation'
docs_dir: '../../docs/en'
site_dir: '../../generated/en'
#repo_url: https://github.com/tudelft3d/3dbag-docs
copyright: Copyright &copy; 2021 3D geoinformation research group, TU Delft
extra_css:
  - stylesheets/extra.css

theme:
  language: en
  custom_dir: '../../overrides/'
  name: material
  favicon: assets/images/logo.svg
  logo: assets/images/logo.svg
  font:
    text: Inter
    code: Roboto Mono
  palette:
    primary: white
    accent: light-blue
  features:
    - navigation.tabs
    - navigation.instant

extra:
  alternate:

    - name: English
      link: /en/
      lang: en

    - name: Nederlands
      link: /nl/
      lang: nl

plugins:
  - search:
      lang: en

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.snippets:
      check_paths: true
      base_path: "."

nav:
  - Overview:
    - 'Summary': index.md
    - 'Data Sources': overview/sources.md
    - 'About Us': 'overview/group.md'
    - 'Release Notes': 'overview/release_notes.md'
  - Schema:
    - 'General Concepts': 'schema/concepts.md'
    - 'Data Layers': 'schema/layers.md'
    - 'Data Attributes': 'schema/attributes.md'
  - 'Data Formats':
      - 'Webservices': 'delivery/webservices.md'
      - 'GeoPackage': 'delivery/gpkg.md'
      - 'CityJSON': 'delivery/cityjson.md'
      - 'PostgreSQL': 'delivery/postgresql.md'
      - 'Wavefront OBJ': 'delivery/obj.md'
  - 'Copyright': 'copyright.md'
  - Contact: contact.md
  - 'Viewer': 'https://3dbag.nl'
